//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TrksRecipeDoc.WikiSpaces.Space {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SpaceBinding", Namespace="urn:Space")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MemberStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TemplateStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Map))]
    public partial class SpaceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback findSpacesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listSpacesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listUserSpacesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listTemplatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSpaceFromTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback renameSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback undeleteSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback isMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback isOrganizerOperationCompleted;
        
        private System.Threading.SendOrPostCallback addMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback addOrganizerOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback listMembersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SpaceService() {
            this.Url = global::TrksRecipeDoc.Properties.Settings.Default.TrksRecipeDoc_WikiSpaces_Space_SpaceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event findSpacesCompletedEventHandler findSpacesCompleted;
        
        /// <remarks/>
        public event listSpacesCompletedEventHandler listSpacesCompleted;
        
        /// <remarks/>
        public event listUserSpacesCompletedEventHandler listUserSpacesCompleted;
        
        /// <remarks/>
        public event listTemplatesCompletedEventHandler listTemplatesCompleted;
        
        /// <remarks/>
        public event getSpaceCompletedEventHandler getSpaceCompleted;
        
        /// <remarks/>
        public event createSpaceCompletedEventHandler createSpaceCompleted;
        
        /// <remarks/>
        public event createSpaceFromTemplateCompletedEventHandler createSpaceFromTemplateCompleted;
        
        /// <remarks/>
        public event updateSpaceCompletedEventHandler updateSpaceCompleted;
        
        /// <remarks/>
        public event deleteSpaceCompletedEventHandler deleteSpaceCompleted;
        
        /// <remarks/>
        public event renameSpaceCompletedEventHandler renameSpaceCompleted;
        
        /// <remarks/>
        public event undeleteSpaceCompletedEventHandler undeleteSpaceCompleted;
        
        /// <remarks/>
        public event isMemberCompletedEventHandler isMemberCompleted;
        
        /// <remarks/>
        public event isOrganizerCompletedEventHandler isOrganizerCompleted;
        
        /// <remarks/>
        public event addMemberCompletedEventHandler addMemberCompleted;
        
        /// <remarks/>
        public event addOrganizerCompletedEventHandler addOrganizerCompleted;
        
        /// <remarks/>
        public event removeMemberCompletedEventHandler removeMemberCompleted;
        
        /// <remarks/>
        public event listMembersCompletedEventHandler listMembersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#findSpaces", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("spaceList")]
        public SpaceStruct[] findSpaces(string session, Map[] filter) {
            object[] results = this.Invoke("findSpaces", new object[] {
                        session,
                        filter});
            return ((SpaceStruct[])(results[0]));
        }
        
        /// <remarks/>
        public void findSpacesAsync(string session, Map[] filter) {
            this.findSpacesAsync(session, filter, null);
        }
        
        /// <remarks/>
        public void findSpacesAsync(string session, Map[] filter, object userState) {
            if ((this.findSpacesOperationCompleted == null)) {
                this.findSpacesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindSpacesOperationCompleted);
            }
            this.InvokeAsync("findSpaces", new object[] {
                        session,
                        filter}, this.findSpacesOperationCompleted, userState);
        }
        
        private void OnfindSpacesOperationCompleted(object arg) {
            if ((this.findSpacesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findSpacesCompleted(this, new findSpacesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#listSpaces", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("spaceList")]
        public SpaceStruct[] listSpaces(string session) {
            object[] results = this.Invoke("listSpaces", new object[] {
                        session});
            return ((SpaceStruct[])(results[0]));
        }
        
        /// <remarks/>
        public void listSpacesAsync(string session) {
            this.listSpacesAsync(session, null);
        }
        
        /// <remarks/>
        public void listSpacesAsync(string session, object userState) {
            if ((this.listSpacesOperationCompleted == null)) {
                this.listSpacesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistSpacesOperationCompleted);
            }
            this.InvokeAsync("listSpaces", new object[] {
                        session}, this.listSpacesOperationCompleted, userState);
        }
        
        private void OnlistSpacesOperationCompleted(object arg) {
            if ((this.listSpacesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listSpacesCompleted(this, new listSpacesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#listUserSpaces", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("spaceList")]
        public SpaceStruct[] listUserSpaces(string session, int userId) {
            object[] results = this.Invoke("listUserSpaces", new object[] {
                        session,
                        userId});
            return ((SpaceStruct[])(results[0]));
        }
        
        /// <remarks/>
        public void listUserSpacesAsync(string session, int userId) {
            this.listUserSpacesAsync(session, userId, null);
        }
        
        /// <remarks/>
        public void listUserSpacesAsync(string session, int userId, object userState) {
            if ((this.listUserSpacesOperationCompleted == null)) {
                this.listUserSpacesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistUserSpacesOperationCompleted);
            }
            this.InvokeAsync("listUserSpaces", new object[] {
                        session,
                        userId}, this.listUserSpacesOperationCompleted, userState);
        }
        
        private void OnlistUserSpacesOperationCompleted(object arg) {
            if ((this.listUserSpacesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listUserSpacesCompleted(this, new listUserSpacesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#listTemplates", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("templateList")]
        public TemplateStruct[] listTemplates(string session) {
            object[] results = this.Invoke("listTemplates", new object[] {
                        session});
            return ((TemplateStruct[])(results[0]));
        }
        
        /// <remarks/>
        public void listTemplatesAsync(string session) {
            this.listTemplatesAsync(session, null);
        }
        
        /// <remarks/>
        public void listTemplatesAsync(string session, object userState) {
            if ((this.listTemplatesOperationCompleted == null)) {
                this.listTemplatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistTemplatesOperationCompleted);
            }
            this.InvokeAsync("listTemplates", new object[] {
                        session}, this.listTemplatesOperationCompleted, userState);
        }
        
        private void OnlistTemplatesOperationCompleted(object arg) {
            if ((this.listTemplatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listTemplatesCompleted(this, new listTemplatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#getSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("space")]
        public SpaceStruct getSpace(string session, string name) {
            object[] results = this.Invoke("getSpace", new object[] {
                        session,
                        name});
            return ((SpaceStruct)(results[0]));
        }
        
        /// <remarks/>
        public void getSpaceAsync(string session, string name) {
            this.getSpaceAsync(session, name, null);
        }
        
        /// <remarks/>
        public void getSpaceAsync(string session, string name, object userState) {
            if ((this.getSpaceOperationCompleted == null)) {
                this.getSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSpaceOperationCompleted);
            }
            this.InvokeAsync("getSpace", new object[] {
                        session,
                        name}, this.getSpaceOperationCompleted, userState);
        }
        
        private void OngetSpaceOperationCompleted(object arg) {
            if ((this.getSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSpaceCompleted(this, new getSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#createSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("space")]
        public SpaceStruct createSpace(string session, string name, string access_level) {
            object[] results = this.Invoke("createSpace", new object[] {
                        session,
                        name,
                        access_level});
            return ((SpaceStruct)(results[0]));
        }
        
        /// <remarks/>
        public void createSpaceAsync(string session, string name, string access_level) {
            this.createSpaceAsync(session, name, access_level, null);
        }
        
        /// <remarks/>
        public void createSpaceAsync(string session, string name, string access_level, object userState) {
            if ((this.createSpaceOperationCompleted == null)) {
                this.createSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSpaceOperationCompleted);
            }
            this.InvokeAsync("createSpace", new object[] {
                        session,
                        name,
                        access_level}, this.createSpaceOperationCompleted, userState);
        }
        
        private void OncreateSpaceOperationCompleted(object arg) {
            if ((this.createSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSpaceCompleted(this, new createSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#createSpaceFromTemplate", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("space")]
        public SpaceStruct createSpaceFromTemplate(string session, string name, string access_level, int templateId) {
            object[] results = this.Invoke("createSpaceFromTemplate", new object[] {
                        session,
                        name,
                        access_level,
                        templateId});
            return ((SpaceStruct)(results[0]));
        }
        
        /// <remarks/>
        public void createSpaceFromTemplateAsync(string session, string name, string access_level, int templateId) {
            this.createSpaceFromTemplateAsync(session, name, access_level, templateId, null);
        }
        
        /// <remarks/>
        public void createSpaceFromTemplateAsync(string session, string name, string access_level, int templateId, object userState) {
            if ((this.createSpaceFromTemplateOperationCompleted == null)) {
                this.createSpaceFromTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSpaceFromTemplateOperationCompleted);
            }
            this.InvokeAsync("createSpaceFromTemplate", new object[] {
                        session,
                        name,
                        access_level,
                        templateId}, this.createSpaceFromTemplateOperationCompleted, userState);
        }
        
        private void OncreateSpaceFromTemplateOperationCompleted(object arg) {
            if ((this.createSpaceFromTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSpaceFromTemplateCompleted(this, new createSpaceFromTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#updateSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("updatedSpace")]
        public SpaceStruct updateSpace(string session, SpaceStruct space) {
            object[] results = this.Invoke("updateSpace", new object[] {
                        session,
                        space});
            return ((SpaceStruct)(results[0]));
        }
        
        /// <remarks/>
        public void updateSpaceAsync(string session, SpaceStruct space) {
            this.updateSpaceAsync(session, space, null);
        }
        
        /// <remarks/>
        public void updateSpaceAsync(string session, SpaceStruct space, object userState) {
            if ((this.updateSpaceOperationCompleted == null)) {
                this.updateSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateSpaceOperationCompleted);
            }
            this.InvokeAsync("updateSpace", new object[] {
                        session,
                        space}, this.updateSpaceOperationCompleted, userState);
        }
        
        private void OnupdateSpaceOperationCompleted(object arg) {
            if ((this.updateSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateSpaceCompleted(this, new updateSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#deleteSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleted")]
        public bool deleteSpace(string session, int spaceId) {
            object[] results = this.Invoke("deleteSpace", new object[] {
                        session,
                        spaceId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteSpaceAsync(string session, int spaceId) {
            this.deleteSpaceAsync(session, spaceId, null);
        }
        
        /// <remarks/>
        public void deleteSpaceAsync(string session, int spaceId, object userState) {
            if ((this.deleteSpaceOperationCompleted == null)) {
                this.deleteSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteSpaceOperationCompleted);
            }
            this.InvokeAsync("deleteSpace", new object[] {
                        session,
                        spaceId}, this.deleteSpaceOperationCompleted, userState);
        }
        
        private void OndeleteSpaceOperationCompleted(object arg) {
            if ((this.deleteSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteSpaceCompleted(this, new deleteSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#renameSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleted")]
        public bool renameSpace(string session, int spaceId, string newName) {
            object[] results = this.Invoke("renameSpace", new object[] {
                        session,
                        spaceId,
                        newName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void renameSpaceAsync(string session, int spaceId, string newName) {
            this.renameSpaceAsync(session, spaceId, newName, null);
        }
        
        /// <remarks/>
        public void renameSpaceAsync(string session, int spaceId, string newName, object userState) {
            if ((this.renameSpaceOperationCompleted == null)) {
                this.renameSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrenameSpaceOperationCompleted);
            }
            this.InvokeAsync("renameSpace", new object[] {
                        session,
                        spaceId,
                        newName}, this.renameSpaceOperationCompleted, userState);
        }
        
        private void OnrenameSpaceOperationCompleted(object arg) {
            if ((this.renameSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.renameSpaceCompleted(this, new renameSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#undeleteSpace", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("undeleted")]
        public bool undeleteSpace(string session, int spaceId) {
            object[] results = this.Invoke("undeleteSpace", new object[] {
                        session,
                        spaceId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void undeleteSpaceAsync(string session, int spaceId) {
            this.undeleteSpaceAsync(session, spaceId, null);
        }
        
        /// <remarks/>
        public void undeleteSpaceAsync(string session, int spaceId, object userState) {
            if ((this.undeleteSpaceOperationCompleted == null)) {
                this.undeleteSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnundeleteSpaceOperationCompleted);
            }
            this.InvokeAsync("undeleteSpace", new object[] {
                        session,
                        spaceId}, this.undeleteSpaceOperationCompleted, userState);
        }
        
        private void OnundeleteSpaceOperationCompleted(object arg) {
            if ((this.undeleteSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.undeleteSpaceCompleted(this, new undeleteSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#isMember", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public bool isMember(string session, int spaceId, int userId) {
            object[] results = this.Invoke("isMember", new object[] {
                        session,
                        spaceId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isMemberAsync(string session, int spaceId, int userId) {
            this.isMemberAsync(session, spaceId, userId, null);
        }
        
        /// <remarks/>
        public void isMemberAsync(string session, int spaceId, int userId, object userState) {
            if ((this.isMemberOperationCompleted == null)) {
                this.isMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisMemberOperationCompleted);
            }
            this.InvokeAsync("isMember", new object[] {
                        session,
                        spaceId,
                        userId}, this.isMemberOperationCompleted, userState);
        }
        
        private void OnisMemberOperationCompleted(object arg) {
            if ((this.isMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isMemberCompleted(this, new isMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#isOrganizer", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public bool isOrganizer(string session, int spaceId, int userId) {
            object[] results = this.Invoke("isOrganizer", new object[] {
                        session,
                        spaceId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isOrganizerAsync(string session, int spaceId, int userId) {
            this.isOrganizerAsync(session, spaceId, userId, null);
        }
        
        /// <remarks/>
        public void isOrganizerAsync(string session, int spaceId, int userId, object userState) {
            if ((this.isOrganizerOperationCompleted == null)) {
                this.isOrganizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisOrganizerOperationCompleted);
            }
            this.InvokeAsync("isOrganizer", new object[] {
                        session,
                        spaceId,
                        userId}, this.isOrganizerOperationCompleted, userState);
        }
        
        private void OnisOrganizerOperationCompleted(object arg) {
            if ((this.isOrganizerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isOrganizerCompleted(this, new isOrganizerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#addMember", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public bool addMember(string session, int spaceId, int userId) {
            object[] results = this.Invoke("addMember", new object[] {
                        session,
                        spaceId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addMemberAsync(string session, int spaceId, int userId) {
            this.addMemberAsync(session, spaceId, userId, null);
        }
        
        /// <remarks/>
        public void addMemberAsync(string session, int spaceId, int userId, object userState) {
            if ((this.addMemberOperationCompleted == null)) {
                this.addMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddMemberOperationCompleted);
            }
            this.InvokeAsync("addMember", new object[] {
                        session,
                        spaceId,
                        userId}, this.addMemberOperationCompleted, userState);
        }
        
        private void OnaddMemberOperationCompleted(object arg) {
            if ((this.addMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addMemberCompleted(this, new addMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#addOrganizer", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public bool addOrganizer(string session, int spaceId, int userId) {
            object[] results = this.Invoke("addOrganizer", new object[] {
                        session,
                        spaceId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addOrganizerAsync(string session, int spaceId, int userId) {
            this.addOrganizerAsync(session, spaceId, userId, null);
        }
        
        /// <remarks/>
        public void addOrganizerAsync(string session, int spaceId, int userId, object userState) {
            if ((this.addOrganizerOperationCompleted == null)) {
                this.addOrganizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddOrganizerOperationCompleted);
            }
            this.InvokeAsync("addOrganizer", new object[] {
                        session,
                        spaceId,
                        userId}, this.addOrganizerOperationCompleted, userState);
        }
        
        private void OnaddOrganizerOperationCompleted(object arg) {
            if ((this.addOrganizerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addOrganizerCompleted(this, new addOrganizerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#removeMember", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public bool removeMember(string session, int spaceId, int userId) {
            object[] results = this.Invoke("removeMember", new object[] {
                        session,
                        spaceId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeMemberAsync(string session, int spaceId, int userId) {
            this.removeMemberAsync(session, spaceId, userId, null);
        }
        
        /// <remarks/>
        public void removeMemberAsync(string session, int spaceId, int userId, object userState) {
            if ((this.removeMemberOperationCompleted == null)) {
                this.removeMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveMemberOperationCompleted);
            }
            this.InvokeAsync("removeMember", new object[] {
                        session,
                        spaceId,
                        userId}, this.removeMemberOperationCompleted, userState);
        }
        
        private void OnremoveMemberOperationCompleted(object arg) {
            if ((this.removeMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeMemberCompleted(this, new removeMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Space#SpaceSOAPApi#listMembers", RequestNamespace="urn:Space", ResponseNamespace="urn:Space")]
        [return: System.Xml.Serialization.SoapElementAttribute("memberList")]
        public MemberStruct[] listMembers(string session, int spaceId) {
            object[] results = this.Invoke("listMembers", new object[] {
                        session,
                        spaceId});
            return ((MemberStruct[])(results[0]));
        }
        
        /// <remarks/>
        public void listMembersAsync(string session, int spaceId) {
            this.listMembersAsync(session, spaceId, null);
        }
        
        /// <remarks/>
        public void listMembersAsync(string session, int spaceId, object userState) {
            if ((this.listMembersOperationCompleted == null)) {
                this.listMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistMembersOperationCompleted);
            }
            this.InvokeAsync("listMembers", new object[] {
                        session,
                        spaceId}, this.listMembersOperationCompleted, userState);
        }
        
        private void OnlistMembersOperationCompleted(object arg) {
            if ((this.listMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listMembersCompleted(this, new listMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.wikispaces.com/space/api")]
    public partial class Map {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.wikispaces.com/space/api")]
    public partial class MemberStruct {
        
        private int userIdField;
        
        private string usernameField;
        
        private string typeField;
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.wikispaces.com/space/api")]
    public partial class TemplateStruct {
        
        private int idField;
        
        private string nameField;
        
        private int space_idField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int space_id {
            get {
                return this.space_idField;
            }
            set {
                this.space_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.wikispaces.com/space/api")]
    public partial class SpaceStruct {
        
        private int idField;
        
        private string nameField;
        
        private string textField;
        
        private string descriptionField;
        
        private string statusField;
        
        private string image_typeField;
        
        private string background_colorField;
        
        private string highlight_colorField;
        
        private string text_colorField;
        
        private string link_colorField;
        
        private string subscription_typeField;
        
        private string subscription_levelField;
        
        private int subscription_end_dateField;
        
        private bool is_crawledField;
        
        private string licenseField;
        
        private string discussionsField;
        
        private int date_createdField;
        
        private int date_updatedField;
        
        private int user_createdField;
        
        private int user_updatedField;
        
        private int page_countField;
        
        private string view_groupField;
        
        private string edit_groupField;
        
        private string create_groupField;
        
        private string message_edit_groupField;
        
        private int editsField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string image_type {
            get {
                return this.image_typeField;
            }
            set {
                this.image_typeField = value;
            }
        }
        
        /// <remarks/>
        public string background_color {
            get {
                return this.background_colorField;
            }
            set {
                this.background_colorField = value;
            }
        }
        
        /// <remarks/>
        public string highlight_color {
            get {
                return this.highlight_colorField;
            }
            set {
                this.highlight_colorField = value;
            }
        }
        
        /// <remarks/>
        public string text_color {
            get {
                return this.text_colorField;
            }
            set {
                this.text_colorField = value;
            }
        }
        
        /// <remarks/>
        public string link_color {
            get {
                return this.link_colorField;
            }
            set {
                this.link_colorField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_type {
            get {
                return this.subscription_typeField;
            }
            set {
                this.subscription_typeField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_level {
            get {
                return this.subscription_levelField;
            }
            set {
                this.subscription_levelField = value;
            }
        }
        
        /// <remarks/>
        public int subscription_end_date {
            get {
                return this.subscription_end_dateField;
            }
            set {
                this.subscription_end_dateField = value;
            }
        }
        
        /// <remarks/>
        public bool is_crawled {
            get {
                return this.is_crawledField;
            }
            set {
                this.is_crawledField = value;
            }
        }
        
        /// <remarks/>
        public string license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        public string discussions {
            get {
                return this.discussionsField;
            }
            set {
                this.discussionsField = value;
            }
        }
        
        /// <remarks/>
        public int date_created {
            get {
                return this.date_createdField;
            }
            set {
                this.date_createdField = value;
            }
        }
        
        /// <remarks/>
        public int date_updated {
            get {
                return this.date_updatedField;
            }
            set {
                this.date_updatedField = value;
            }
        }
        
        /// <remarks/>
        public int user_created {
            get {
                return this.user_createdField;
            }
            set {
                this.user_createdField = value;
            }
        }
        
        /// <remarks/>
        public int user_updated {
            get {
                return this.user_updatedField;
            }
            set {
                this.user_updatedField = value;
            }
        }
        
        /// <remarks/>
        public int page_count {
            get {
                return this.page_countField;
            }
            set {
                this.page_countField = value;
            }
        }
        
        /// <remarks/>
        public string view_group {
            get {
                return this.view_groupField;
            }
            set {
                this.view_groupField = value;
            }
        }
        
        /// <remarks/>
        public string edit_group {
            get {
                return this.edit_groupField;
            }
            set {
                this.edit_groupField = value;
            }
        }
        
        /// <remarks/>
        public string create_group {
            get {
                return this.create_groupField;
            }
            set {
                this.create_groupField = value;
            }
        }
        
        /// <remarks/>
        public string message_edit_group {
            get {
                return this.message_edit_groupField;
            }
            set {
                this.message_edit_groupField = value;
            }
        }
        
        /// <remarks/>
        public int edits {
            get {
                return this.editsField;
            }
            set {
                this.editsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void findSpacesCompletedEventHandler(object sender, findSpacesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findSpacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findSpacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listSpacesCompletedEventHandler(object sender, listSpacesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listSpacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listSpacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listUserSpacesCompletedEventHandler(object sender, listUserSpacesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listUserSpacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listUserSpacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listTemplatesCompletedEventHandler(object sender, listTemplatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listTemplatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listTemplatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TemplateStruct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TemplateStruct[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getSpaceCompletedEventHandler(object sender, getSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createSpaceCompletedEventHandler(object sender, createSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createSpaceFromTemplateCompletedEventHandler(object sender, createSpaceFromTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSpaceFromTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSpaceFromTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateSpaceCompletedEventHandler(object sender, updateSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SpaceStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SpaceStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteSpaceCompletedEventHandler(object sender, deleteSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void renameSpaceCompletedEventHandler(object sender, renameSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class renameSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal renameSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void undeleteSpaceCompletedEventHandler(object sender, undeleteSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class undeleteSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal undeleteSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void isMemberCompletedEventHandler(object sender, isMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void isOrganizerCompletedEventHandler(object sender, isOrganizerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isOrganizerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isOrganizerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addMemberCompletedEventHandler(object sender, addMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addOrganizerCompletedEventHandler(object sender, addOrganizerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addOrganizerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addOrganizerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void removeMemberCompletedEventHandler(object sender, removeMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void listMembersCompletedEventHandler(object sender, listMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MemberStruct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MemberStruct[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591